import { useEffect, useState, type ReactNode } from 'react';
import { useI18n } from '../i18n';
import type { TranslationKey } from '../i18n/types';
import type { WsEvent } from '../hooks/useWebSocket';
import { getConsensusAnalytics, saveEvaluationFeedback, type ConsensusAnalyticsData, type EvaluationBatch, type EvaluationFeedback } from '../api/consensusAnalytics';

const percent = (value: number | null) => value===null ? '—' : `${(value*100).toFixed(1)}%`;
const number = (value: number | null | undefined) => value===null || value===undefined ? '—' : value.toLocaleString();
const money = (value: number,coverage: number | null) => coverage===null || coverage===0 ? '—' : `$${value.toFixed(4)} (${percent(coverage)})`;
const milliseconds = (value: number | null) => value===null ? '—' : `${Math.round(value).toLocaleString()} ms`;
function EvaluationTable({ headers,rows }: { headers: string[]; rows: ReactNode[][] }) {
  return <div className="overflow-x-auto"><table className="w-full text-xs text-left"><thead><tr>{headers.map((h,i)=><th key={i} className="p-2 text-theme-muted font-medium whitespace-nowrap">{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i} className="border-t border-theme-border">{row.map((cell,j)=><td key={j} className="p-2 align-top">{cell}</td>)}</tr>)}</tbody></table></div>;
}
function FeedbackControl({ projectId,batchId,scope,jobId,fingerprint,current,onSaved }: { projectId: string; batchId: string; scope: 'batch' | 'reviewer_job' | 'issue'; jobId?: string; fingerprint?: string; current?: EvaluationFeedback; onSaved: () => void }) {
  const { t }=useI18n();
  const choices=scope==='batch' ? ['correct','incorrect','mixed','unknown'] : scope==='reviewer_job' ? ['useful','not_useful','mixed','unknown'] : ['confirmed','rejected','uncertain'];
  const [label,setLabel]=useState(current?.label ?? choices.at(-1)!);const [note,setNote]=useState(current?.note ?? '');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  useEffect(()=>{ setLabel(current?.label ?? choices.at(-1)!);setNote(current?.note ?? ''); },[current?.id,current?.label,current?.note,scope]);
  return <form className="flex flex-wrap items-center gap-2 mt-2" onSubmit={async event=>{ event.preventDefault();setBusy(true);setError('');try { await saveEvaluationFeedback(projectId,batchId,scope,label,note,jobId,fingerprint);onSaved(); } catch { setError(t('evaluation.saveError')); } finally { setBusy(false); } }}>
    <label className="text-xs text-theme-muted">{t('evaluation.feedback')}<select aria-label={t('evaluation.feedback')} className="ml-2 bg-theme-card rounded-xl p-2" value={label} onChange={e=>setLabel(e.target.value)}>{choices.map(choice=><option key={choice} value={choice}>{t(`evaluation.label.${choice}` as TranslationKey)}</option>)}</select></label>
    <input className="input-field text-xs" aria-label={t('evaluation.note')} placeholder={t('evaluation.note')} value={note} maxLength={4096} onChange={e=>setNote(e.target.value)} />
    <button className="btn-ghost text-xs" disabled={busy}>{t('common.save')}</button>{current && <span className="text-xs text-theme-muted">{t('evaluation.saved')}</span>}{error && <span role="alert" className="text-status-error">{error}</span>}
  </form>;
}
function BatchEvaluation({ projectId,batch,onSaved }: { projectId: string; batch: EvaluationBatch; onSaved: () => void }) {
  const { t }=useI18n();const label=(key: string)=>t(`evaluation.${key}` as TranslationKey);
  return <div className="panel space-y-3">
    <p className="text-xs">{batch.id} · {t(`consensus.status.${batch.status}`)} · {batch.finalVerdict ? t(`review.pipeline.verdict.${batch.finalVerdict}`) : '—'}</p>
    <EvaluationTable headers={['agreement','providers','accounts','models','unique','judgeChanged','knownCost','knownTokens'].map(label)} rows={[[batch.agreement===null ? '—' : label(batch.agreement ? 'agreement' : 'disagreement'),batch.diversity.distinctProviders,batch.diversity.distinctAccounts,batch.diversity.distinctModels,batch.uniqueIssueCount,batch.judge.overrodeMajority===null ? '—' : Number(batch.judge.overrodeMajority),money(batch.telemetry.knownCostUsd,batch.telemetry.costCoverage),`${number(batch.telemetry.knownTokens)} (${percent(batch.telemetry.tokenCoverage)})`]]} />
    <FeedbackControl projectId={projectId} batchId={batch.id} scope="batch" current={batch.feedback.find(f=>f.scope==='batch')} onSaved={onSaved} />
    {batch.jobs.map(job=><div key={job.id} className="rounded-xl bg-theme-card p-3">
      <p className="text-sm font-medium">{job.label} · {[job.identity.provider,job.identity.providerAccountLabel ?? job.identity.providerAccountId,job.identity.effectiveModel,job.identity.effort].map(v=>v??'—').join(' / ')}</p>
      <p className="text-xs text-theme-muted">{label('decisive')}: {job.decisiveVote===null ? '—' : Number(job.decisiveVote)} · {label('judgeTrigger')}: {Number(job.judgeTriggerContribution)} · {label('unique')}: {job.uniqueIssueCount}</p>
      <FeedbackControl projectId={projectId} batchId={batch.id} jobId={job.id} scope="reviewer_job" current={job.feedback.find(f=>f.scope==='reviewer_job')} onSaved={onSaved} />
      {job.issues.map(issue=><div key={issue.fingerprint} className="mt-3 pl-3 border-l border-theme-border"><p className="text-xs">{t(`review.pipeline.severity.${issue.severity}`)} · {issue.description} · {issue.files?.join(', ')}</p><FeedbackControl projectId={projectId} batchId={batch.id} jobId={job.id} fingerprint={issue.fingerprint} scope="issue" current={job.feedback.find(f=>f.issue_fingerprint===issue.fingerprint)} onSaved={onSaved} /></div>)}
    </div>)}
    <p className="text-xs text-theme-muted">{label('humanActions')}: {batch.humanActions.map(a=>`${label(`action.${a.action}`)} (${a.created_at})`).join(', ') || '—'}</p>
  </div>;
}
export default function ConsensusAnalyticsPanel({ projectId,onEvent }: { projectId: string; onEvent?: (cb: (event: WsEvent) => void) => () => void }) {
  const { t }=useI18n();const label=(key: string)=>t(`evaluation.${key}` as TranslationKey);
  const [period,setPeriod]=useState('all'),[offset,setOffset]=useState(0),[revision,setRevision]=useState(0),[data,setData]=useState<ConsensusAnalyticsData>(),[error,setError]=useState(''),[loading,setLoading]=useState(false),[selected,setSelected]=useState<string>(),[view,setView]=useState('member');
  const [filters,setFilters]=useState<Record<string,string>>({});
  useEffect(()=>{ let disposed=false;setLoading(true);setError('');setData(undefined);getConsensusAnalytics(projectId,period,offset,filters).then(value=>{ if (!disposed) setData(value); }).catch(()=>{ if (!disposed) setError(label('loadError')); }).finally(()=>{ if (!disposed) setLoading(false); });return ()=>{ disposed=true; }; },[projectId,period,offset,revision,filters]);
  useEffect(()=>onEvent?.(event=>{ if (event.type==='review-evaluation:feedback-updated' && event.projectId===projectId) setRevision(v=>v+1); }),[projectId,onEvent]);
  const refresh=()=>setRevision(v=>v+1);
  const section=(title: string,headers: string[],rows: ReactNode[][])=><section className="panel"><h4 className="text-sm font-semibold mb-3">{label(title)}</h4><EvaluationTable headers={headers.map(label)} rows={rows} /></section>;
  return <div className="space-y-4">
    <p className="panel text-sm text-theme-text-secondary">{label('evidence')}</p>
    <div className="flex flex-wrap gap-2">{['7d','30d','90d','all'].map(p=><button key={p} className={`btn-ghost text-xs ${period===p ? 'text-accent' : ''}`} onClick={()=>{ setPeriod(p);setOffset(0); }}>{t(`analytics.period.${p}`)}</button>)}<button className="btn-ghost text-xs" onClick={refresh}>{label('refresh')}</button><a className="btn-ghost text-xs text-accent" href={`/api/projects/${encodeURIComponent(projectId)}/analytics/consensus/export.csv?${new URLSearchParams({ period,offset: String(offset),...Object.fromEntries(Object.entries(filters).filter(([,v])=>v)) })}`}>{label('export')}</a></div>
    <div className="flex flex-wrap gap-2">{['reviewPolicyId','strategy','executionProfileId','provider','providerAccountId','model'].map(key=><label key={key} className="text-xs text-theme-muted">{label(`filter.${key}`)}<input className="input-field block text-xs" value={filters[key]??''} onChange={e=>{ setFilters(v=>({ ...v,[key]: e.target.value }));setOffset(0); }} /></label>)}</div>
    {error && <p role="alert" className="text-status-error">{error}</p>}{loading && <p className="text-xs text-theme-muted">{label('loading')}</p>}
    {data && <>
      <p className="text-xs text-theme-muted">{data.period.periodStart??'—'} — {data.period.periodEnd} · {data.period.timezone} · {label('reported')}</p>
      {data.summary.sampleCount<10 && <p className="text-xs text-status-warning">{label('lowSample')} ({data.summary.sampleCount})</p>}
      {(data.bounds.groupRowsOmitted || data.bounds.issueRowsOmitted || data.bounds.dailyRowsOmitted) && <p className="text-xs text-status-warning">{label('bounded')}</p>}
      <div className="panel flex flex-wrap gap-x-8 gap-y-3">{[['batches',number(data.summary.totalBatches)],['agreement',percent(data.summary.agreementRate)],['disagreement',percent(data.summary.disagreementRate)],['rework',percent(data.summary.reworkRate)],['failed',number(data.summary.failedBatches)],['judgeUse',percent(data.summary.judgeInvocationRate)],['knownCost',money(data.summary.knownCostUsd,data.summary.costCoverage)],['knownTokens',`${number(data.summary.knownTokens)} (${percent(data.summary.tokenCoverage)})`]].map(([key,value])=><div key={key}><p className="text-xs text-theme-muted">{label(key)}</p><p className="text-lg font-semibold tabular-nums">{value}</p></div>)}</div>
      {section('daily',['date','batches','agreement','disagreement'],data.daily.map(d=>[d.date,d.batches,d.agreement,d.disagreement]))}
      {section('strategies',['strategy','batches','agreement','rework','failed','judgeUse','knownCost','duration'],data.strategies.map(s=>[t(`consensus.${s.strategy}`),s.totalBatches,percent(s.agreementRate),percent(s.reworkRate),s.failedBatches,percent(s.judgeInvocationRate),money(s.knownCostUsd,s.costCoverage),milliseconds(s.avgBatchDurationMs)]))}
      {section('policies',['policy','variant','batches','agreement','rework','knownCost'],data.policies.map(p=>[p.policyId,p.policyVariantId.slice(0,12),p.totalBatches,percent(p.agreementRate),percent(p.reworkRate),money(p.knownCostUsd,p.costCoverage)]))}
      <section className="panel"><h4 className="text-sm font-semibold">{label('reviewers')}</h4><div className="flex flex-wrap gap-2 my-2">{['member','provider','provider_model','provider_account','provider_account_model'].map(v=><button key={v} className={`btn-ghost text-xs ${view===v ? 'text-accent' : ''}`} onClick={()=>setView(v)}>{label(`view.${v}`)}</button>)}</div><EvaluationTable headers={['identity','jobs','approved','needsChanges','alignment','unique','confirmed','rejected','knownCost','duration','sample'].map(label)} rows={(view==='member' ? data.reviewers : data.executionIdentities.filter(r=>r.grouping===view)).map(r=>[r.label ? `${r.label} (${r.policyMemberId})` : Object.values(r.identity??{}).map(v=>v??'—').join(' / '),r.jobs,r.approvalVotes,r.needsChangesVotes,percent(r.finalAlignmentRate),r.uniqueIssueCount,r.confirmedFindingCount,r.rejectedFindingCount,money(r.knownCostUsd,r.telemetryCoverage.cost),milliseconds(r.avgDurationMs),`${r.sampleCount}${r.sampleCount<10 ? ` · ${label('lowSample')}` : ''}`])} /></section>
      {section('diversity',['identity','batches','agreement','rework','knownCost'],data.diversity.map(d=>[label(`cohort.${d.cohort}`),d.totalBatches,percent(d.agreementRate),percent(d.reworkRate),money(d.knownCostUsd,d.costCoverage)]))}
      {section('judge',['judgeUse','completed','failed','judgeChanged','knownCost','duration'],[[data.judge.judgeInvocations,data.judge.judgeCompleted,data.judge.judgeFailed,data.judge.judgeOverrodeMajority,money(data.judge.knownJudgeCostUsd,data.judge.judgeCostCoverage),milliseconds(data.judge.avgJudgeDurationMs)]])}
      {section('issues',['description','files','severity','reviewers','batches','unique','shared','confirmed','rejected'],data.issues.map(i=>[i.description,i.files?.join(', ')??'—',t(`review.pipeline.severity.${i.severity}`),i.reviewerCount,i.batchCount,i.uniqueCount,i.sharedCount,i.confirmed,i.rejected]))}
      {section('feedback',['batchCoverage','reviewerCoverage','issueCoverage','confirmed','rejected'],[[percent(data.humanFeedback.batchFeedbackCoverage),percent(data.humanFeedback.reviewerFeedbackCoverage),`${data.summary.feedbackIssuesLabeled} / ${data.summary.feedbackIssuesTotal} (${percent(data.humanFeedback.issueFeedbackCoverage)})`,data.humanFeedback.confirmedIssueCount,data.humanFeedback.rejectedIssueCount]])}
      {section('comparison',['cohort','batches','needsChanges','rework','knownCost','knownTokens','duration'],[[label('single'),data.singleBaseline.singleReviewRounds,data.singleBaseline.singleNeedsChanges,percent(data.singleBaseline.singleReworkRate),money(data.singleBaseline.knownCostUsd,data.singleBaseline.costCoverage),'—',milliseconds(data.singleBaseline.avgDurationMs)],[label('consensus'),data.summary.totalBatches,data.summary.needsChangesBatches,percent(data.summary.reworkRate),money(data.summary.knownCostUsd,data.summary.costCoverage),`${number(data.summary.knownTokens)} (${percent(data.summary.tokenCoverage)})`,milliseconds(data.summary.avgBatchDurationMs)]])}
      <section className="panel"><h4 className="text-sm font-semibold mb-2">{label('batches')}</h4><div className="flex flex-wrap gap-2">{data.batches.map(b=><button key={b.id} className="btn-ghost text-xs" onClick={()=>setSelected(selected===b.id ? undefined : b.id)}>{b.id.slice(0,8)} · {t(`consensus.status.${b.status}`)}</button>)}</div><div className="flex items-center gap-3 mt-3 text-xs"><button className="btn-ghost" disabled={!offset} onClick={()=>setOffset(Math.max(0,offset-200))}>{label('previous')}</button><span>{offset+1}–{offset+data.batches.length} / {data.pagination.total}</span><button className="btn-ghost" disabled={!data.pagination.hasMore} onClick={()=>setOffset(offset+200)}>{label('next')}</button></div></section>
      {data.batches.find(b=>b.id===selected) && <BatchEvaluation key={selected} projectId={projectId} batch={data.batches.find(b=>b.id===selected)!} onSaved={refresh} />}
    </>}
  </div>;
}
