import { useEffect, useState } from 'react';
import { useI18n } from '../i18n';
import type { WsEvent } from '../hooks/useWebSocket';
import { listCampaigns, saveCampaign, campaignAction, deleteCampaign, getCampaignAnalytics, getCampaignAssignments, downloadCampaignCsv, type Campaign, type CampaignArm, type CampaignAnalytics, type CampaignMetrics, type AssignmentPage } from '../api/evaluationCampaigns';
import { getProfiles, type ExecutionProfile } from '../api/executionProfiles';
import { getPolicies, type ReviewPolicy } from '../api/consensusReview';
import Modal from './Modal';
import CampaignAssignmentDetails from './CampaignAssignmentDetails';

const emptyArm=(is_control: number,sort_order: number): CampaignArm=>({ name: '',description: '',is_control,weight: 1,sort_order,is_enabled: 1,review_mode: 'single',review_profile_id: null,review_policy_id: null,rework_profile_id: null,max_review_rounds: null });
const value=(n: number | null | undefined)=>n===null || n===undefined ? '—' : Number.isInteger(n) ? String(n) : n.toFixed(3);
const percent=(n: number | null)=>n===null ? '—' : `${(n*100).toFixed(1)}%`;
export default function EvaluationCampaignsPanel({ projectId,onEvent }: { projectId: string; onEvent?: (cb: (event: WsEvent)=>void)=>()=>void }) {
  const { t }=useI18n();
  const [campaigns,setCampaigns]=useState<Campaign[]>([]),[selected,setSelected]=useState(''),[revision,setRevision]=useState(0),[analytics,setAnalytics]=useState<CampaignAnalytics>(),[page,setPage]=useState<AssignmentPage>(),[offset,setOffset]=useState(0),[protocol,setProtocol]=useState<'itt' | 'pp'>('itt'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[archived,setArchived]=useState(false),[assignmentTodo,setAssignmentTodo]=useState('');
  const [editor,setEditor]=useState<{ id?: string; locked: boolean; name: string; description: string; auto_enroll: number; max_assignments: number | null; arms: CampaignArm[] }>(),[profiles,setProfiles]=useState<ExecutionProfile[]>([]),[policies,setPolicies]=useState<ReviewPolicy[]>([]);
  useEffect(()=>onEvent?.(event=>{ if (event.type.startsWith('evaluation-campaign:') && 'projectId' in event && event.projectId===projectId || event.type==='todo:status-changed' || event.type==='todo:round-updated') setRevision(v=>v+1); }),[onEvent,projectId]);
  useEffect(()=>{ let disposed=false;listCampaigns(projectId,archived).then(data=>{ if (!disposed) setCampaigns(data); }).catch(()=>{ if (!disposed) setError(t('campaign.loadError')); });return ()=>{ disposed=true; }; },[projectId,revision,archived,t]);
  useEffect(()=>{ let disposed=false;setAnalytics(undefined);setPage(undefined);if (selected) Promise.all([getCampaignAnalytics(selected,projectId),getCampaignAssignments(selected,projectId,offset)]).then(([data,p])=>{ if (!disposed) { setAnalytics(data);setPage(p); } }).catch(()=>{ if (!disposed) setError(t('campaign.loadError')); });return ()=>{ disposed=true; }; },[projectId,selected,offset,revision,t]);
  useEffect(()=>{ void getProfiles(false).then(setProfiles).catch(()=>setError(t('campaign.loadError')));void getPolicies().then(setPolicies).catch(()=>setError(t('campaign.loadError'))); },[]);
  const campaign=campaigns.find(c=>c.id===selected);
  async function act(action: ()=>Promise<unknown>) { setBusy(true);setError('');try { await action();setRevision(v=>v+1); } catch { setError(t('campaign.actionError')); } finally { setBusy(false); } }
  function edit(c?: Campaign) { setEditor(c ? { id: c.id,locked: c.status!=='draft',name: c.name,description: c.description,auto_enroll: c.auto_enroll,max_assignments: c.max_assignments,arms: c.arms.map(a=>({ id: a.id,name: a.name,description: a.description,is_control: a.is_control,weight: a.weight,sort_order: a.sort_order,is_enabled: a.is_enabled,review_mode: a.review_mode,review_profile_id: a.review_profile_id,review_policy_id: a.review_policy_id,rework_profile_id: a.rework_profile_id,max_review_rounds: a.max_review_rounds })) }
    : { locked: false,name: '',description: '',auto_enroll: 0,max_assignments: null,arms: [emptyArm(1,0),emptyArm(0,1)] }); }
  function changeArm(index: number,patch: Partial<CampaignArm>) { setEditor(old=>old ? { ...old,arms: old.arms.map((a,i)=>i===index ? { ...a,...patch } : a) } : old); }
  const comparisonKeys=['completionRate','failureRate','reworkRate','needsChangesRate','avgTreatmentCostUsd','p50TreatmentCostUsd','avgTodoDurationMs','helpfulRate'];
  const metricKeys: (keyof Omit<CampaignMetrics,'feedback' | 'lowSample'>)[]=['assignments','started','reachedReview','terminal','completed','failed','stopped','approvedFinalReview','needsChangesFinalReview','finalReviewSamples','todosWithRework','reworkDenominator','reworkRate','manualApprove','manualRework','avgTodoDurationMs','p50TodoDurationMs','p95TodoDurationMs','durationSamples','knownTreatmentCostUsd','treatmentCostAttemptsKnown','treatmentCostAttemptsTotal','treatmentCostCoverage','treatmentCostTodosFullyCovered','treatmentCostTodosStarted','treatmentCostTodoCoverage','avgTreatmentCostUsd','p50TreatmentCostUsd','knownTreatmentIoTokens','treatmentTokenAttemptsKnown','treatmentTokenAttemptsTotal','treatmentTokenCoverage','knownCacheReadTokens','cacheReadCoverage','knownCacheCreationTokens','cacheCreationCoverage','knownAttemptWallDurationMs','attemptWallDurationCoverage','knownProviderDurationMs','providerDurationCoverage','treatmentProcessAttempts'];
  return <div className="space-y-4 text-theme-text">
    <div className="flex gap-3 items-center"><h2 className="font-semibold">{t('campaign.title')}</h2><button className="btn-primary text-sm" onClick={()=>edit()}>{t('campaign.create')}</button><label className="text-xs"><input type="checkbox" checked={archived} onChange={e=>setArchived(e.target.checked)} /> {t('campaign.showArchived')}</label></div>
    {error && <p role="alert" className="text-status-error">{error}</p>}
    {!campaigns.length && <p className="text-theme-muted">{t('campaign.empty')}</p>}
    <div className="overflow-x-auto"><table className="w-full text-xs text-left"><thead><tr>{['name','status','assigned','arms','control','started','clean'].map(key=><th className="p-2" key={key}>{t(`campaign.${key}`)}</th>)}</tr></thead><tbody>{campaigns.map(c=><tr className="border-t border-theme-border" key={c.id}><td className="p-2"><button className="text-accent" onClick={()=>{ setSelected(c.id);setOffset(0); }}>{c.name}</button></td><td>{t(`campaign.${c.status}`)}</td><td>{c.assigned} / {c.max_assignments ?? '—'}</td><td>{c.arms.filter(a=>a.is_enabled).length}</td><td>{c.arms.find(a=>a.is_control)?.name}</td><td>{c.started_at ? new Date(c.started_at).toLocaleString() : '—'}</td><td>{percent(c.cleanPercentage)}</td></tr>)}</tbody></table></div>
    {campaign && <section className="card p-4 space-y-4">
      <div className="flex gap-2 flex-wrap items-center"><h3 className="font-semibold">{campaign.name}</h3><button className="btn-ghost text-xs" onClick={()=>edit(campaign)}>{t('campaign.edit')}</button>
        {(campaign.status==='draft' ? ['start','delete'] : campaign.status==='running' ? ['pause','complete'] : campaign.status==='paused' ? ['resume','complete'] : campaign.status==='completed' ? ['archive'] : []).map(action=><button disabled={busy} className="btn-ghost text-xs" key={action} onClick={()=>void act(()=>action==='delete' ? deleteCampaign(campaign.id,projectId).then(()=>setSelected('')) : campaignAction(campaign.id,projectId,action))}>{t(`campaign.${action}`)}</button>)}
        <button disabled={busy} className="btn-ghost text-xs" onClick={()=>void act(()=>campaignAction(campaign.id,projectId,'clone'))}>{t('campaign.clone')}</button>
        <button disabled={busy} className="btn-ghost text-xs" onClick={()=>void act(()=>downloadCampaignCsv(campaign.id,projectId))}>{t('campaign.csv')}</button>
      </div>
      {campaign.status==='draft' && <p className="text-sm text-theme-muted">{t('campaign.startWarning')}</p>}
      <p className="text-xs break-all">{t('campaign.algorithm')}: {campaign.assignment_algorithm} · {t('campaign.definitionHash')}: {campaign.campaign_definition_hash ?? '—'}</p>
      <div className="flex gap-2">{(['itt','pp'] as const).map(p=><button aria-pressed={protocol===p} className={protocol===p?'btn-primary text-xs':'btn-ghost text-xs'} onClick={()=>setProtocol(p)} key={p}>{t(`campaign.${p}`)}</button>)}</div>
      <p className="text-xs text-theme-muted">{t(`campaign.${protocol}Help`)} {t('campaign.costCaveat')}</p>
      {analytics && <>
        <div className="overflow-x-auto"><table className="text-xs w-full text-left"><thead><tr><th>{t('campaign.metric')}</th>{analytics.arms.map(a=><th className="p-2" key={a.id}>{a.name} · {t(a.isControl?'campaign.control':'campaign.experiment')}{a[protocol].lowSample && <div className="text-status-warning">{t('campaign.lowSample')}</div>}</th>)}</tr></thead><tbody>
          {['expectedPercentage','observedPercentage','observedCount','clean','contaminated','excluded'].map(key=><tr className="border-t border-theme-border" key={key}><td className="p-2">{t(`campaign.${key}`)}</td>{analytics.arms.map(a=><td key={a.id}>{key.endsWith('Percentage') ? percent(a[key as 'expectedPercentage']) : value(a[key as 'observedCount'])}</td>)}</tr>)}
          {metricKeys.map(key=><tr className="border-t border-theme-border" key={key}><td className="p-2">{t(`campaign.${key}`)}</td>{analytics.arms.map(a=><td key={a.id}>{key.endsWith('Coverage') || key.endsWith('Rate') ? percent(a[protocol][key]) : value(a[protocol][key])}</td>)}</tr>)}
          {['responses','evaluative','denominator','helpful','notHelpful','mixed','unknown','helpfulRate','responseCoverage','evaluativeCoverage'].map(key=><tr className="border-t border-theme-border" key={key}><td className="p-2">{t(`campaign.${key}`)}</td>{analytics.arms.map(a=><td key={a.id}>{key.endsWith('Rate') || key.endsWith('Coverage') ? percent(a[protocol].feedback[key as 'responses']) : value(a[protocol].feedback[key as 'responses'])}</td>)}</tr>)}
        </tbody></table></div>
        {analytics.comparisons.map(c=><div key={c.armId} className="overflow-x-auto"><h4 className="text-sm font-medium">{analytics.arms.find(a=>a.id===c.armId)?.name}</h4><table className="w-full text-xs text-left"><thead><tr>{['metric','control','experiment','difference','ratio'].map(key=><th className="p-2" key={key}>{t(`campaign.${key}`)}</th>)}</tr></thead><tbody>{comparisonKeys.map(key=><tr className="border-t border-theme-border" key={key}><td className="p-2">{t(`campaign.${key}`)}</td>{[c[protocol][key].controlValue,c[protocol][key].armValue,c[protocol][key].absoluteDifference,c[protocol][key].relativeRatio].map((v,i)=><td key={i}>{value(v)}</td>)}</tr>)}</tbody></table></div>)}
        <details><summary>{t('campaign.identities')}</summary>{analytics.arms.map(a=><div className="p-2 text-xs" key={a.id}><strong>{a.name}</strong>{Object.entries(a.actualIdentities[protocol]).map(([key,group])=><div key={key}>{t(`campaign.${key}`)}: {group.items.map(i=>`${i.value}: ${i.todos}`).join(' · ')}{group.omittedIdentities>0 && ` (+${group.omittedIdentities})`}</div>)}</div>)}</details>
      </>}
      {page && <div className="space-y-2"><h4>{t('campaign.assignments')}</h4>{page.assignments.map(a=><button className="block text-xs text-accent" key={a.assignment_id} onClick={()=>setAssignmentTodo(a.todo_id)}>{a.todo_id} · {a.arm_name} · {t(`campaign.${a.integrity_state}`)} · {t(`status.${a.todo_status}`)}</button>)}<div className="flex gap-2"><button className="btn-ghost text-xs" disabled={!offset} onClick={()=>setOffset(v=>Math.max(0,v-100))}>{t('campaign.previous')}</button><span className="text-xs">{offset+page.assignments.length} / {page.total}</span><button className="btn-ghost text-xs" disabled={!page.hasMore} onClick={()=>setOffset(v=>v+100)}>{t('campaign.next')}</button></div></div>}
    </section>}
    {assignmentTodo && <Modal open onClose={()=>setAssignmentTodo('')}><CampaignAssignmentDetails todoId={assignmentTodo} projectId={projectId} revision={revision} /></Modal>}
    {editor && <Modal open onClose={()=>setEditor(undefined)} size="lg"><form className="card p-4 space-y-3 max-h-[85vh] overflow-y-auto" onSubmit={e=>{ e.preventDefault();void act(async()=>{ const saved=await saveCampaign(projectId,editor.locked ? { name: editor.name,description: editor.description } : { name: editor.name,description: editor.description,auto_enroll: editor.auto_enroll,max_assignments: editor.max_assignments,arms: editor.arms },editor.id);setSelected(saved.id);setOffset(0);setEditor(undefined); }); }}>
      <h3 className="font-semibold">{t(editor.id?'campaign.edit':'campaign.create')}</h3>
      <label className="block text-xs">{t('campaign.name')}<input className="input-field w-full" required maxLength={128} value={editor.name} onChange={e=>setEditor({ ...editor,name: e.target.value })} /></label>
      <label className="block text-xs">{t('campaign.description')}<textarea className="input-field w-full" maxLength={4096} value={editor.description} onChange={e=>setEditor({ ...editor,description: e.target.value })} /></label>
      <fieldset disabled={editor.locked} className="space-y-3 disabled:opacity-60">
        <label className="text-sm"><input type="checkbox" checked={!!editor.auto_enroll} onChange={e=>setEditor({ ...editor,auto_enroll: e.target.checked?1:0 })} /> {t('campaign.autoEnroll')}</label>
        <label className="block text-xs">{t('campaign.maxAssignments')}<input type="number" min={2} max={100000} className="input-field" value={editor.max_assignments ?? ''} onChange={e=>setEditor({ ...editor,max_assignments: e.target.value ? Number(e.target.value) : null })} /></label>
        {editor.arms.map((arm,index)=><div key={arm.id ?? index} className="rounded-xl border border-theme-border p-3 space-y-2">
          <label className="block text-xs">{t('campaign.armName')}<input required maxLength={128} className="input-field w-full" value={arm.name} onChange={e=>changeArm(index,{ name: e.target.value })} /></label>
          <label className="text-xs"><input type="radio" name="control" checked={!!arm.is_control} onChange={()=>setEditor({ ...editor,arms: editor.arms.map((a,i)=>({ ...a,is_control: i===index?1:0 })) })} /> {t('campaign.control')}</label>
          <label className="block text-xs">{t('campaign.weight')}<input type="number" min={1} max={1000} required className="input-field" value={arm.weight} onChange={e=>changeArm(index,{ weight: Number(e.target.value) })} /></label>
          <label className="block text-xs">{t('consensus.mode')}<select className="input-field" value={arm.review_mode} onChange={e=>changeArm(index,{ review_mode: e.target.value as 'single' | 'consensus',review_profile_id: null,review_policy_id: null })}><option value="single">{t('consensus.single')}</option><option value="consensus">{t('consensus.consensus')}</option></select></label>
          <label className="block text-xs">{t(arm.review_mode==='single'?'review.pipeline.reviewProfile':'consensus.policy')}<select required className="input-field w-full" value={(arm.review_mode==='single'?arm.review_profile_id:arm.review_policy_id) ?? ''} onChange={e=>changeArm(index,arm.review_mode==='single'?{ review_profile_id: e.target.value || null }:{ review_policy_id: e.target.value || null })}><option value="">{t('campaign.select')}</option>{(arm.review_mode==='single'?profiles:policies.filter(p=>p.is_enabled)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
          <label className="block text-xs">{t('review.pipeline.reworkProfile')}<select className="input-field w-full" value={arm.rework_profile_id ?? ''} onChange={e=>changeArm(index,{ rework_profile_id: e.target.value || null })}><option value="">{t('todoForm.worktreeInherit')}</option>{profiles.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
          <label className="block text-xs">{t('review.pipeline.maxRounds')}<input type="number" min={1} max={10} className="input-field" value={arm.max_review_rounds ?? ''} onChange={e=>changeArm(index,{ max_review_rounds: e.target.value ? Number(e.target.value) : null })} /></label>
          {editor.arms.length>2 && <button type="button" className="btn-ghost text-xs" onClick={()=>setEditor({ ...editor,arms: editor.arms.filter((_,i)=>i!==index) })}>{t('campaign.removeArm')}</button>}
        </div>)}
        {editor.arms.length<6 && <button type="button" className="btn-ghost text-xs" onClick={()=>setEditor({ ...editor,arms: [...editor.arms,emptyArm(0,editor.arms.length)] })}>{t('campaign.addArm')}</button>}
      </fieldset>
      {editor.locked && <p className="text-xs">{t('campaign.locked')}</p>}
      {error && <p role="alert" className="text-status-error">{error}</p>}
      <button disabled={busy} className="btn-primary text-sm">{t('campaign.save')}</button>
    </form></Modal>}
  </div>;
}
