import fs from 'node:fs';
import express from 'express';
import os from 'node:os';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
import { randomUUID } from 'node:crypto';

const alias = process.argv[2];
const remoteRoot = process.argv[3];
if (!alias || !remoteRoot) throw new Error('Usage: tsx scripts/resource-fabric-smoke.ts <ssh-alias> <disposable-remote-root>');
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'aikombinat-resource-smoke-'));
process.env.DB_PATH = path.join(root, 'smoke.db');
process.env.AIKOMBINAT_LOG_DIR = path.join(root, 'logs');
const { getDatabase, closeDatabase } = await import('../src/server/db/connection.js');
const queries = await import('../src/server/db/queries.js');
const { resourceFabric, getComputeNodes, getResourceInstances, resourceLeaseTotals } = await import('../src/server/services/resource-fabric.js');
const { resourceManager } = await import('../src/server/services/resource-manager.js');
const { orchestrator } = await import('../src/server/services/orchestrator.js');
const { matchResources } = await import('../src/server/services/resource-matcher.js');
const { sshTransport } = await import('../src/server/services/execution-transport.js');
const { parseProcessIdentity } = await import('../src/server/utils/process-tree.js');
const { sshArgs, shellQuote } = await import('../src/server/services/resource-probes.js');
const db = getDatabase();
const local = getComputeNodes().find(node => node.transport === 'local')!;
const remote = resourceFabric.createSshNode('Smoke SSH node', { host: alias, auth_mode: 'config', workspace_root: remoteRoot });
const connection = await resourceFabric.testConnection(remote.id);
if (connection.status !== 'connected') throw new Error(connection.error ?? connection.status);
await resourceFabric.scan(local.id);
await resourceFabric.scan(remote.id);
resourceFabric.updatePolicy(local.id, { ...getComputeNodes().find(node => node.id === local.id)!.policy, cpu_reserve_threads: 8, memory_reserve_bytes: 16 * 1024 ** 3 });
const nodes = getComputeNodes(), instances = getResourceInstances(), leased = resourceLeaseTotals();
const candidates = nodes.map(node => ({ node, instances: instances.filter(instance => instance.node_id === node.id), leased }));
const matrix = [
  { version: 2 as const, requires: { resources: [{ kind: 'gpu' as const, count: 1, model: 'RTX 5060 Ti' }] }, prefers: {} },
  { version: 2 as const, requires: { platform: { os: 'linux', distro: 'ubuntu' }, resources: [{ kind: 'gpu' as const, count: 2, min_vram_bytes: 8 * 1024 ** 3, same_node: true }] }, prefers: {} },
  { version: 2 as const, requires: { resources: [{ kind: 'gpu' as const, count: 2, min_vram_bytes: 16 * 1024 ** 3, same_node: true }] }, prefers: {} },
].map(requirements => ({ requirements, decision: matchResources(requirements, candidates) }));
const workspace = path.join(root, 'fixture'); fs.mkdirSync(workspace);
fs.writeFileSync(path.join(workspace, 'README.md'), 'Disposable Resource Fabric V2 smoke fixture\n');
const git = (args: string[]) => execFileSync('git', args, { cwd: workspace, windowsHide: true, encoding: 'utf8' }).trim();
git(['init']); git(['add', 'README.md']); git(['-c', 'user.name=Resource smoke', '-c', 'user.email=smoke@example.invalid', 'commit', '-m', 'Disposable fixture']);
const project = queries.createProject(`Resource smoke ${randomUUID()}`, workspace);
queries.updateProject(project.id, { cli_tool: 'raw-shell', use_worktree: 0, npm_auto_install: 0, sandbox_mode: 'permissive' });
const todo = queries.createTodo(project.id, 'Disposable remote fixture', `python3 -c "import time; from pathlib import Path; time.sleep(4); Path('result.txt').write_text('RESOURCE_FABRIC_V2_OK\\n'); print('RESOURCE_FABRIC_V2_OK')"`);
queries.updateTodo(todo.id, { cli_tool: 'raw-shell', use_worktree: 0, resource_requirements: JSON.stringify({ version: 2, requires: { node_id: remote.id, platform: { os: 'linux', distro: 'ubuntu' }, cpu: { threads: 1 }, memory: { bytes: 64 * 1024 ** 2 } }, prefers: {} }) });
resourceFabric.updatePolicy(remote.id, { ...getComputeNodes().find(node => node.id === remote.id)!.policy, cpu_reserve_threads: getComputeNodes().find(node => node.id === remote.id)!.inventory!.cpu.logical_threads - 1 });
resourceManager.initialize();
resourceManager.setAvailabilityCallback(() => { setImmediate(() => { void orchestrator.wakeWaitingResources(); }); });
const router = (await import('../src/server/routes/resources.js')).default;
const app = express(); app.use('/api', router);
const server = await new Promise<import('node:http').Server>(resolve => { const started = app.listen(0, '127.0.0.1', () => resolve(started)); });
const port = (server.address() as import('node:net').AddressInfo).port;
await orchestrator.startTodo(todo.id, 'headless');
const running = queries.getTodoById(todo.id)!;
const identity = parseProcessIdentity(running.process_identity);
const identityVerdict = identity?.remote ? await sshTransport.inspect(identity.remote) : null;
const ownership = await (await fetch(`http://127.0.0.1:${port}/api/resources/leases`)).json() as { leases: Array<{ owner_id: string; process_pid: number; node_id: string }> };
const waitingWorkspace = path.join(root, 'second-fixture');
execFileSync('git', ['clone', workspace, waitingWorkspace], { windowsHide: true });
const waitingProject = queries.createProject('Separate admission smoke', waitingWorkspace);
queries.updateProject(waitingProject.id, { cli_tool: 'raw-shell', use_worktree: 0, npm_auto_install: 0, sandbox_mode: 'permissive' });
const waiting = queries.createTodo(waitingProject.id, 'Queued disposable fixture', 'python3 -c "print(123)"');
queries.updateTodo(waiting.id, { cli_tool: 'raw-shell', use_worktree: 0, resource_requirements: queries.getTodoById(todo.id)!.resource_requirements });
await orchestrator.startTodo(waiting.id, 'headless');
const waitingStatus = queries.getTodoById(waiting.id)!.status;
const deadline = Date.now() + 90_000;
while ([todo.id, waiting.id].some(id => !['completed', 'failed'].includes(queries.getTodoById(id)!.status)) && Date.now() < deadline) await new Promise(resolve => setTimeout(resolve, 500));
const finished = queries.getTodoById(todo.id)!;
const execution = db.prepare('SELECT * FROM remote_executions WHERE binding_id = (SELECT id FROM resource_bindings WHERE request_id IN (SELECT id FROM resource_requests WHERE owner_id = ?))').get(todo.id) as { workspace: string; status: string; exit_code: number; identity_json: string } | undefined;
const result = execution ? execFileSync('ssh', sshArgs(remote.connection!, `cat ${shellQuote(execution.workspace + '/repo/result.txt')}`), { timeout: 8000, encoding: 'utf8', windowsHide: true }).trim() : '';
const stopping = queries.createTodo(project.id, 'Own stop fixture', 'python3 -c "import time; time.sleep(30)"');
queries.updateTodo(stopping.id, { cli_tool: 'raw-shell', use_worktree: 0, resource_requirements: queries.getTodoById(todo.id)!.resource_requirements });
await orchestrator.startTodo(stopping.id, 'headless');
const stopPid = queries.getTodoById(stopping.id)!.process_pid;
resourceFabric.updateNode(remote.id, { scheduler_state: 'draining' });
const drainLeases = (db.prepare('SELECT COUNT(*) AS n FROM resource_leases WHERE owner_id = ?').get(stopping.id) as { n: number }).n;
resourceFabric.updateNode(remote.id, { scheduler_state: 'maintenance' });
const maintenanceLeases = (db.prepare('SELECT COUNT(*) AS n FROM resource_leases WHERE owner_id = ?').get(stopping.id) as { n: number }).n;
await orchestrator.stopTodo(stopping.id); await sshTransport.whenExited(stopPid);
resourceFabric.updateNode(remote.id, { scheduler_state: 'online' });
await new Promise<void>((resolve, reject) => server.close(error => error ? reject(error) : resolve()));
const checks = { waiting_status: waitingStatus, wake_status: queries.getTodoById(waiting.id)!.status, owner_api_verified: ownership.leases.some(lease => lease.owner_id === todo.id && lease.process_pid === identity?.pid && lease.node_id === remote.id), drain_retains_ownership: drainLeases === 2, maintenance_retains_ownership: maintenanceLeases === 2, own_stop_status: queries.getTodoById(stopping.id)!.status };
const report = { checks, timestamp: new Date().toISOString(), commit: execFileSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf8' }).trim(), os: `${os.platform()} ${os.release()}`, node: process.version, nodes: getComputeNodes().map(({ connection: _connection, ...node }) => node), instances, matcher: matrix, remote: { todo_status: finished.status, pid: identity?.pid, identity_verdict: identityVerdict?.verdict, execution_status: execution?.status, exit_code: execution?.exit_code, result, leases_remaining: db.prepare('SELECT COUNT(*) AS count FROM resource_leases').get() }, local_artifacts: root };
fs.mkdirSync('logs', { recursive: true }); fs.writeFileSync('logs/resource-fabric-v2-smoke.json', JSON.stringify(report, null, 2));
resourceManager.shutdown(); resourceFabric.shutdown(); closeDatabase();
process.stdout.write(JSON.stringify({ status: finished.status, result, report: path.resolve('logs/resource-fabric-v2-smoke.json') }) + '\n');
if (finished.status !== 'completed' || result !== 'RESOURCE_FABRIC_V2_OK' || checks.waiting_status !== 'waiting_resource' || checks.wake_status !== 'completed' || !checks.owner_api_verified || !checks.drain_retains_ownership || !checks.maintenance_retains_ownership || checks.own_stop_status !== 'stopped') process.exitCode = 1;
