import type { ClientPluginManifest } from '../types';
import HarnessPanel from './HarnessPanel';
import HarnessSettings from './HarnessSettings';

export const harnessClientPlugin: ClientPluginManifest = {
  id: 'harness',
  displayName: 'Harness',
  displayNameKo: '하네스',
  displayNameRu: 'Harness',
  PanelComponent: HarnessPanel,
  SettingsComponent: HarnessSettings,
  hasTab: false,
  isEnabled: (project) => !!project.path,
  translations: {
    en: {
      'tabs.harness': 'Harness',
      'tabs.harness.help': 'Edit your global Claude/Antigravity/Codex CLI config — settings, memory, and MCP servers — without leaving the project. Note: changes affect your user-level CLI dirs, not the worktree.',
      'harness.settingsTitle': 'Harness Configuration',
      'harness.settingsDesc': 'Edit Claude / Antigravity / Codex CLI settings, memory files, and MCP servers.',
      'harness.loading': 'Loading harness configuration…',
      'harness.cli.claude': 'Claude',
      'harness.cli.antigravity': 'Antigravity',
      'harness.cli.codex': 'Codex',
      'harness.section.settings': 'Settings',
      'harness.section.mcp': 'MCP Servers',
      'harness.field.model': 'Model',
      'harness.field.modelPlaceholder.claude': 'e.g. claude-sonnet-4-6',
      'harness.field.modelPlaceholder.antigravity': 'e.g. leave blank for default',
      'harness.field.modelPlaceholder.codex': 'e.g. gpt-5',
      'harness.field.approvalMode': 'Approval Mode',
      'harness.field.sandbox': 'Sandbox',
      'harness.field.unset': '(unset)',
      'harness.save': 'Save',
      'harness.saving': 'Saving…',
      'harness.cancel': 'Cancel',
      'harness.edit': 'Edit',
      'harness.delete': 'Delete',
      'harness.noChanges': 'No changes',
      'harness.memory.placeholder': 'Project context the AI should always know about (preferences, conventions, key files)…',
      'harness.memory.expand': 'Expand editor',
      'harness.memory.collapse': 'Collapse editor',
      'harness.localMemory.create': 'Create CLAUDE.local.md',
      'harness.memory.resize': 'Drag to resize, double-click to reset',
      'harness.find.open': 'Find (Ctrl+F)',
      'harness.find.placeholder': 'Find… (Enter: next, Shift+Enter: previous)',
      'harness.find.prev': 'Previous match',
      'harness.find.next': 'Next match',
      'harness.find.close': 'Close (Esc)',
      'harness.hooks.empty': 'No hooks configured.',
      'harness.hooks.editJson': 'Edit JSON',
      'harness.hooks.invalidJson': 'Invalid JSON — fix the syntax and try again.',
      'harness.skills.empty': 'No skills in .claude/skills/.',
      'harness.mcp.add': 'Add Server',
      'harness.mcp.empty': 'No MCP servers configured.',
      'harness.mcp.addTitle': 'Add MCP Server',
      'harness.mcp.editTitle': 'Edit MCP Server',
      'harness.mcp.alias': 'Alias',
      'harness.mcp.transport': 'Transport',
      'harness.mcp.command': 'Command',
      'harness.mcp.args': 'Arguments (space-separated)',
      'harness.mcp.env': 'Environment (one KEY=VALUE per line)',
      'harness.mcp.url': 'URL',
      'harness.mcp.headers': 'Headers (one KEY=VALUE per line)',
      'harness.mcp.confirmRemove': 'Remove MCP server "{alias}"?',
      'harness.mcp.errAlias': 'Alias is required.',
      'harness.mcp.errAliasExists': 'An MCP server with this alias already exists.',
      'harness.mcp.errCommand': 'Command is required for stdio transport.',
      'harness.mcp.errUrl': 'URL is required for HTTP/SSE transport.',
      'harness.warning.worktreeIsolation.title': 'Edits apply outside AIKombinat worktrees',
      'harness.warning.worktreeIsolation.body':
        'Changes are saved to the project root. CLI tools launched directly from your terminal pick them up immediately. AIKombinat todos run inside .worktrees/<branch>/, so tracked files (CLAUDE.md, .claude/settings.json) are only included once you commit, and untracked files (.mcp.json, settings.local.json) are not copied automatically.',
      'harness.warning.tomlComments': 'Note: saving Codex config.toml via this UI may strip existing comments. Edit the file in a text editor if you want to preserve them.',
      'harness.warning.codexTrustLevel.title': 'Codex trust level required',
      'harness.warning.codexTrustLevel.body':
        'Codex only loads project-level config.toml when this project is marked trusted in your user-global ~/.codex/config.toml. Add the snippet below to enable it:',
    },
    ko: {
      'tabs.harness': '하네스',
      'tabs.harness.help': 'Claude/Antigravity/Codex의 사용자 설정·메모리·MCP 서버를 한 곳에서 편집. 변경은 worktree가 아니라 사용자 글로벌 CLI 디렉토리에 적용됩니다.',
      'harness.settingsTitle': '하네스 구성',
      'harness.settingsDesc': 'Claude / Antigravity / Codex CLI 설정·메모리 파일·MCP 서버를 편집합니다.',
      'harness.loading': '하네스 구성 불러오는 중…',
      'harness.cli.claude': 'Claude',
      'harness.cli.antigravity': 'Antigravity',
      'harness.cli.codex': 'Codex',
      'harness.section.settings': '설정',
      'harness.section.mcp': 'MCP 서버',
      'harness.field.model': '모델',
      'harness.field.modelPlaceholder.claude': '예: claude-sonnet-4-6',
      'harness.field.modelPlaceholder.antigravity': '예: 비워두면 기본값',
      'harness.field.modelPlaceholder.codex': '예: gpt-5',
      'harness.field.approvalMode': '승인 모드',
      'harness.field.sandbox': '샌드박스',
      'harness.field.unset': '(미설정)',
      'harness.save': '저장',
      'harness.saving': '저장 중…',
      'harness.cancel': '취소',
      'harness.edit': '편집',
      'harness.delete': '삭제',
      'harness.noChanges': '변경사항 없음',
      'harness.memory.placeholder': 'AI가 항상 알고 있어야 할 프로젝트 컨텍스트(취향, 컨벤션, 주요 파일)…',
      'harness.memory.expand': '에디터 확대',
      'harness.memory.collapse': '에디터 축소',
      'harness.localMemory.create': 'CLAUDE.local.md 만들기',
      'harness.memory.resize': '드래그로 높이 조절, 더블클릭으로 초기화',
      'harness.find.open': '찾기 (Ctrl+F)',
      'harness.find.placeholder': '찾기… (Enter: 다음, Shift+Enter: 이전)',
      'harness.find.prev': '이전 결과',
      'harness.find.next': '다음 결과',
      'harness.find.close': '닫기 (Esc)',
      'harness.hooks.empty': '설정된 hook이 없습니다.',
      'harness.hooks.editJson': 'JSON 편집',
      'harness.hooks.invalidJson': 'JSON 형식이 올바르지 않습니다. 수정 후 다시 저장하세요.',
      'harness.skills.empty': '.claude/skills/ 에 스킬이 없습니다.',
      'harness.mcp.add': '서버 추가',
      'harness.mcp.empty': '등록된 MCP 서버가 없습니다.',
      'harness.mcp.addTitle': 'MCP 서버 추가',
      'harness.mcp.editTitle': 'MCP 서버 편집',
      'harness.mcp.alias': '별칭',
      'harness.mcp.transport': '전송 방식',
      'harness.mcp.command': '명령어',
      'harness.mcp.args': '인자 (공백 구분)',
      'harness.mcp.env': '환경 변수 (한 줄에 KEY=VALUE)',
      'harness.mcp.url': 'URL',
      'harness.mcp.headers': '헤더 (한 줄에 KEY=VALUE)',
      'harness.mcp.confirmRemove': 'MCP 서버 "{alias}" 을(를) 삭제할까요?',
      'harness.mcp.errAlias': '별칭은 필수입니다.',
      'harness.mcp.errAliasExists': '이미 같은 별칭의 MCP 서버가 있습니다.',
      'harness.mcp.errCommand': 'stdio 전송 방식에는 명령어가 필요합니다.',
      'harness.mcp.errUrl': 'HTTP/SSE 전송 방식에는 URL이 필요합니다.',
      'harness.warning.worktreeIsolation.title': '편집 사항은 AIKombinat worktree 밖에 적용됩니다',
      'harness.warning.worktreeIsolation.body':
        '변경 사항은 프로젝트 루트에 저장됩니다. 터미널에서 CLI를 직접 띄울 때는 바로 적용되지만, AIKombinat의 todo는 .worktrees/<branch>/ 안에서 실행되므로 추적 파일(CLAUDE.md, .claude/settings.json)은 커밋해야 다음 worktree 생성 시 반영되고, untracked 파일(.mcp.json, settings.local.json)은 자동으로 복사되지 않습니다.',
      'harness.warning.tomlComments': '참고: 이 UI로 Codex config.toml을 저장하면 기존 주석이 사라질 수 있습니다. 주석을 보존하려면 텍스트 에디터에서 직접 편집하세요.',
      'harness.warning.codexTrustLevel.title': 'Codex 신뢰 수준이 필요합니다',
      'harness.warning.codexTrustLevel.body':
        'Codex는 ~/.codex/config.toml에 이 프로젝트가 trusted로 등록된 경우에만 프로젝트별 config.toml을 읽습니다. 아래 스니펫을 추가하세요:',
    },
  },
};
